### ISSUE TITLE
"_eeschema.dll" R2 not working

### ISSUE THREAD

**Issue by htduan** [j0t/kicad87#1]
Tried to replace "_eeschema.dll" under \bin with the one provided in R2 for KiCAD 8.0.5 on Win 7, but schematic editor crashes right after  start. The modified R2 version of "_eeschema.dll" is only 45 kB in size, which is considerably smaller than the one provided by the official KiCAD package (15419 kB).

**Comment by j0t** [comment]
Did you RENAME the original `_eeschema.dll` to `__eeschema.dll`? The suggested `_eeschema.dll` (a "small" one) is just a wrapper which mostly intercepts all requests from `eeschema.exe` (or whatever) and forwards them to the original `__eeschema.dll` (a "big" one).

**Comment by htduan** [comment]
Sorry, my bad. I misunderstood the purpose of a "wrapper", and renamed the original "_eeschema.dll" differently. Now the schematic editor works flawlessly on Win 7, even with KiCAD 8.0.7. Thanks a lot for your excellent work!
